# Generated by Django 4.2.27 on 2026-07-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_zero_amount_voucher_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='intent_type',
            field=models.CharField(choices=[('checkout_session', 'Checkout Session'), ('payment_intent', 'Payment Intent'), ('voucher_free', 'Voucher (no card charge)'), ('manual_tutor', 'Manual (paid to tutor)')], max_length=20),
        ),
    ]
