-- Going Digital — schema reference
-- Production uses MySQL / MariaDB (utf8mb4). Authoritative DDL: Django migrations
--   python manage.py migrate
-- Inspect SQL for a migration: python manage.py sqlmigrate <app> <name>
