# Generated by Django 4.2.27 on 2026-06-26 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_newsletter_modal_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettermodalsettings',
            name='desktop_focus_x',
            field=models.PositiveSmallIntegerField(default=85, help_text='Desktop: horizontal focus (0 = left edge, 100 = right edge).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='newslettermodalsettings',
            name='desktop_focus_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Desktop: vertical focus (0 = top, 100 = bottom).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='newslettermodalsettings',
            name='mobile_focus_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Mobile: horizontal focus (0 = left, 100 = right).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='newslettermodalsettings',
            name='mobile_focus_y',
            field=models.PositiveSmallIntegerField(default=25, help_text='Mobile: vertical focus (0 = top, 100 = bottom).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
