# Generated by Django 4.2.27 on 2026-06-26 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_newslettermodalsettings_desktop_focus_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettermodalsettings',
            name='desktop_zoom',
            field=models.PositiveSmallIntegerField(default=100, help_text='Desktop: 100 = default crop; increase to zoom in on the focal point.', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='newslettermodalsettings',
            name='mobile_zoom',
            field=models.PositiveSmallIntegerField(default=100, help_text='Mobile: 100 = default crop; increase to zoom in on the focal point.', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
