# Generated by Django 4.2.27 on 2026-08-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_workshop_reminder_email_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(help_text='Recommended size: 1000×667 px (3:2) for landscape-oriented screens, or a tall portrait crop for phones. Text overlay is fixed on the homepage.', upload_to='hero-images/'),
        ),
    ]
