# Generated by Django 5.1.1 on 2026-01-17 13:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Full course description')),
                ('short_description', models.CharField(help_text='Brief summary for listings', max_length=500)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('category', models.CharField(choices=[('portrait', 'Portrait Photography'), ('landscape', 'Landscape Photography'), ('wedding', 'Wedding Photography'), ('street', 'Street Photography'), ('product', 'Product Photography'), ('wildlife', 'Wildlife Photography'), ('macro', 'Macro Photography'), ('astrophotography', 'Astrophotography'), ('general', 'General Photography')], max_length=50)),
                ('duration_hours', models.PositiveIntegerField(help_text='Course duration in hours')),
                ('max_students', models.PositiveIntegerField(default=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('what_youll_learn', models.JSONField(default=list, help_text="List of learning outcomes (e.g., ['Learn aperture', 'Understand composition'])")),
                ('audience', models.TextField(help_text='Who this course is for')),
                ('prerequisites', models.TextField(blank=True, help_text='Required knowledge/equipment')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course')),
            ],
            options={
                'db_table': 'course_faqs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/')),
                ('specialties', models.CharField(help_text='Comma-separated list of specialties', max_length=255)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructors',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('enrollment_open', models.BooleanField(default=True)),
                ('current_students', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override base course price for this instance', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='courses.course')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instances', to='franchises.location')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_instances', to='courses.instructor')),
            ],
            options={
                'db_table': 'course_instances',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date', 'location'], name='course_inst_start_d_17dd5a_idx'), models.Index(fields=['course', 'location'], name='course_inst_course__123e20_idx')],
            },
        ),
    ]
