# Generated by Django 5.1.1 on 2026-01-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended size: 1000x667 pixels (3:2 aspect ratio)', upload_to='hero-images/')),
                ('title', models.CharField(help_text="Hero title text (e.g., 'Start Your Photography Journey')", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Hero subtitle text (optional)', max_length=500)),
                ('cta_text', models.CharField(default='Explore Courses', help_text='Call-to-action button text', max_length=100)),
                ('cta_link', models.CharField(default='#journey', help_text="Link for CTA button (e.g., '#journey' or '/courses/')", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this image in the hero slider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'db_table': 'hero_images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
