# Generated by Django 5.1.1 on 2026-01-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_heroimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroimage',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='heroimage',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='heroimage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='heroimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(help_text='Recommended size: 1000x667 pixels (3:2 aspect ratio). Text overlay is fixed on the homepage.', upload_to='hero-images/'),
        ),
    ]
