# Generated by Django 5.1.1 on 2026-01-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_heroimage_cta_link_remove_heroimage_cta_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=200)),
                ('role', models.CharField(blank=True, help_text="Customer's role/occupation (e.g., 'Amateur Photographer', 'Wedding Photographer')", max_length=200)),
                ('testimonial_text', models.TextField(help_text='The testimonial content (recommended: 2-3 sentences)')),
                ('image', models.ImageField(blank=True, help_text='Optional: Customer photo (recommended: 200x200 pixels, square)', null=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
