# Generated by Django 5.1.1 on 2026-01-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='course_date',
            field=models.DateField(blank=True, help_text='Date when the course was taken (optional)', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Rating out of 5 stars'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='venue',
            field=models.CharField(blank=True, help_text="Location where the course was taken (e.g., 'London Studio', 'Manchester')", max_length=200),
        ),
    ]
