# Generated by Django 4.2.27 on 2026-01-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_testimonial_course_date_testimonial_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description of this before/after comparison', max_length=200)),
                ('before_image', models.ImageField(help_text='Original/unedited image', upload_to='editing-before-after/before/')),
                ('after_image', models.ImageField(help_text='Edited/final image', upload_to='editing-before-after/after/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this before/after comparison on the editing courses page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Before/After Image',
                'verbose_name_plural': 'Before/After Images',
                'db_table': 'before_after_images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
