# Generated by Django 4.2.27 on 2026-03-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_courseinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['user__lastname', 'user__firstname']},
        ),
    ]
