# Generated by Django 4.2.27 on 2026-03-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_fix_workshop_created_updated_zero_dates'),
        # Merge graph: 0024 is only referenced by bookings.0003; tie it into courses leaves.
        ('courses', '0024_create_gd_workshop_gd_venue_if_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_name',
            field=models.CharField(db_column='file_name', max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_size',
            field=models.IntegerField(db_column='file_size'),
        ),
        migrations.AlterField(
            model_name='image',
            name='mime_type',
            field=models.CharField(db_column='mime_type', max_length=20),
        ),
    ]
