# Generated by Django 4.2.27 on 2026-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_region_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_category_id',
            field=models.IntegerField(blank=True, db_column='image_category_id', null=True, verbose_name='Image category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type_id',
            field=models.IntegerField(blank=True, db_column='image_type_id', null=True, verbose_name='Image type'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.IntegerField(blank=True, db_column='user_id', null=True, verbose_name='User'),
        ),
    ]
