# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_workshop_date_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueDocumentEmailSetting',
            fields=[
                (
                    'venue_id',
                    models.IntegerField(
                        help_text='gd_venue.id',
                        primary_key=True,
                        serialize=False,
                        verbose_name='Venue ID',
                    ),
                ),
                (
                    'include_in_booking_email',
                    models.BooleanField(
                        default=False,
                        verbose_name='Add to booking email',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Venue document email setting',
                'verbose_name_plural': 'Venue document email settings',
            },
        ),
    ]
