# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_venue_document_email_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuedocumentemailsetting',
            name='include_in_booking_email',
            field=models.BooleanField(
                default=True,
                verbose_name='Add to booking email',
            ),
        ),
    ]
