# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_alter_venuedocumentemailsetting_include_in_booking_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='workshop_documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mimetype', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                (
                    'include_in_booking_email',
                    models.BooleanField(default=True, verbose_name='Add to booking email'),
                ),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('createdby_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'workshop',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documents',
                        to='courses.workshop',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Workshop document',
                'verbose_name_plural': 'Workshop documents',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
