# Generated by Django 4.2.27 on 2026-07-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_regionuser_foreign_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='GdDocument',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('document_type_id', models.IntegerField(db_column='document_type_id')),
                ('document_category_id', models.IntegerField(db_column='document_category_id')),
                ('active', models.SmallIntegerField(db_column='active', default=1)),
                ('title', models.CharField(db_column='title', max_length=1000)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('source_filename', models.CharField(db_column='source_filename', max_length=1000)),
                ('document_filename', models.CharField(db_column='document_filename', max_length=1000)),
                ('mimetype', models.CharField(blank=True, db_column='mimetype', max_length=255, null=True)),
                ('filesize', models.IntegerField(blank=True, db_column='filesize', null=True)),
                ('downloads', models.IntegerField(db_column='downloads', default=0)),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
            ],
            options={
                'verbose_name': 'Legacy document',
                'verbose_name_plural': 'Legacy documents',
                'db_table': 'gd_document',
                'ordering': ['title'],
                'managed': False,
            },
        ),
    ]
