# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0048_tutor_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueContentChangeRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_title', models.CharField(blank=True, default='', max_length=1000)),
                ('strapline', models.TextField(blank=True, default='')),
                ('main_content', models.TextField(blank=True, default='')),
                ('sub_content', models.TextField(blank=True, default='')),
                ('meta_title', models.TextField(blank=True, default='')),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='')),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending review'), ('rejected', 'Rejected')],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'requested_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'venue',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='content_change_request',
                        to='courses.venue',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Venue content change request',
                'verbose_name_plural': 'Venue content change requests',
                'db_table': 'gd_venue_content_change_request',
            },
        ),
    ]
