# Generated by Django 4.2.27 on 2026-03-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_migrate_to_workshop'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_worksho_d46e71_idx',
            old_name='bookings_workshop_status_idx',
        ),
    ]
