# Generated by Django 4.2.27 on 2026-03-21 18:54

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_payment_currency'),
        ('bookings', '0004_rename_bookings_workshop_status_idx_bookings_worksho_d46e71_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('basket_id', models.IntegerField(blank=True, db_column='basket_id', null=True)),
                ('active', models.IntegerField(db_column='active', default=1)),
                ('voucher_type_id', models.IntegerField(blank=True, db_column='voucher_type_id', null=True)),
                ('use_once', models.IntegerField(db_column='use_once', default=0)),
                ('voucher_group_id', models.IntegerField(blank=True, db_column='voucher_group_id', null=True)),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', null=True)),
                ('customer_id', models.IntegerField(blank=True, db_column='customer_id', null=True)),
                ('claimed_by_customer_id', models.IntegerField(blank=True, db_column='claimed_by_customer_id', null=True)),
                ('claimed_on_booking_id', models.IntegerField(blank=True, db_column='claimed_on_booking_id', null=True)),
                ('region_id', models.IntegerField(blank=True, db_column='region_id', null=True)),
                ('course_ids', models.TextField(blank=True, db_column='course_ids', null=True)),
                ('workshop_id', models.IntegerField(blank=True, db_column='workshop_id', null=True)),
                ('actioned', models.IntegerField(db_column='actioned', default=0)),
                ('email', models.CharField(blank=True, db_column='email', max_length=255, null=True)),
                ('issue_date', courses.models.SafeDateField(blank=True, db_column='issue_date', null=True)),
                ('expiry_date', courses.models.SafeDateField(blank=True, db_column='expiry_date', null=True)),
                ('value', models.DecimalField(blank=True, db_column='value', decimal_places=2, max_digits=10, null=True)),
                ('voucher_code', models.CharField(db_column='voucher_code', default='', max_length=255)),
                ('claimed_date', courses.models.SafeDateField(blank=True, db_column='claimed_date', null=True)),
                ('amount_claimed', models.DecimalField(db_column='amount_claimed', decimal_places=2, default=0, max_digits=7)),
                ('payment_gateway_id', models.IntegerField(blank=True, db_column='payment_gateway_id', null=True)),
                ('gateway_transaction_code', models.CharField(blank=True, db_column='gateway_transaction_code', max_length=255, null=True)),
                ('transaction_percentage_on_creation', models.DecimalField(blank=True, db_column='transaction_percentage_on_creation', decimal_places=2, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('minimum_workshops', models.IntegerField(blank=True, db_column='minimum_workshops', null=True)),
                ('allowed_course', models.IntegerField(blank=True, db_column='allowed_course', null=True)),
                ('createdby_id', models.IntegerField(blank=True, db_column='createdby_id', null=True)),
                ('updatedby_id', models.IntegerField(blank=True, db_column='updatedby_id', null=True)),
                ('created_at', courses.models.SafeDateTimeField(blank=True, db_column='created_at', null=True)),
                ('updated_at', courses.models.SafeDateTimeField(blank=True, db_column='updated_at', null=True)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'db_table': 'gd_voucher',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GiftVoucherOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchaser_name', models.CharField(max_length=200)),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('purchaser_phone', models.CharField(blank=True, max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('gift_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('voucher_sent', 'Voucher Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_voucher_order', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_voucher_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gift_voucher_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
