# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_email_sent_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the day-before workshop reminder email was sent to the student.',
                null=True,
            ),
        ),
    ]
