# Generated by Django 4.2.27 on 2026-03-20 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('franchises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type_id': 3}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_franchises', to=settings.AUTH_USER_MODEL),
        ),
    ]
